### ISSUE TITLE
tighten up lists

### ISSUE THREAD

**Issue by vapier** [Umbyology/OGL-SRD5#13]
the source md files insert blank lines between list items which causes the rendered output to take up a lot of wasted space.  can those all get trimmed ?

for example, the spell lists:
https://ogl-srd5.com/spellcasting#spelllists

there's so much dead space here because the md looks like:
```
- Dancing Lights

- Light

- Mage Hand
```

and the html looks like (should omit `<p>` entirely):
```
<ul>
<li>
<p>Dancing Lights</p>
</li>
<li>
<p>Light</p>
</li>
<li>
<p>Mage Hand</p>
</li>
```

**Comment by Umbyology** [comment]
It looks like you may be pulling the data/material from the website directly. If you want to utilize the material in a project, you need to pull from the Github files which are VERY clean Markdown Text and contain no HTML. The website is for searching and reading only. We are working on a new render of the website, stay tuned. THX!

**Comment by vapier** [comment]
the markdown files in the github repo have the same problem.  please see the example i showed in the initial comment.  the blank lines between the individual items causes a lot of dead space.

that said, i showed the rendered html content also is not great.  presumably it's related.

**Comment by Umbyology** [comment]
Done.
