### ISSUE TITLE
linkify spellcasting lists

### ISSUE THREAD

**Issue by vapier** [Umbyology/OGL-SRD5#14]
can all the spell lists be turned into proper links ?  for example, the bard summary should have every spell linked to its description.

```

## Bard Spells

#### Cantrips (0 Level)

- [Dancing Lights](#Dancing-Lights)
- [Light](#Light)
- [Mage Hand](#Mage-Hand)
- [Mending](#Mending)
- [Message](#Message)
- [Minor Illusion](#Minor-Illusion)
- [Prestidigitation](#Prestidigitation)
- [True Strike](#True-Strike)
```

**Comment by Umbyology** [comment]
We are working on that. Check the Changelog for more information on upcoming features.

**Comment by Umbyology** [comment]
For this project, there will be no linking as the code would interfere with the nature of the project; to assist others in their own 5E publications. THX!
