### ISSUE TITLE
Druid spell list is missing entries

### ISSUE THREAD

**Issue by vapier** [Umbyology/OGL-SRD5#15]
the [Druid cantrips section](https://ogl-srd5.com/spellcasting#cantrips0level-2) is missing a few entries:
* Druidcraft
* Poison Spray
* Thorn Whip

the 1st level is missing:
* Animal Friendship
* Goodberry

the 2nd level is missing:
* Beast Sense

the 3rd level is missing:
* Feign Death

seems like the lists need auditing

**Comment by Umbyology** [comment]
Good catch, unsure what happened there. We'll double-check the spell lists again. We have an updated version of both the markdown and .docx files. Stay tuned. THX!

**Comment by Umbyology** [comment]
The difference is between the D&D 5E SRD 5.0 and 5.1.  Apparently, Wizards changed the spell lists. We're going thru the lists now comparing and adjusting. THX!

**Comment by Umbyology** [comment]
UPDATE: Just a reminder, not all spells are included in the 5E SRD, the Druid spell "Thorn Whip" is NOT included, and in-fact, v5.1 actually removes some additional spells.

We have completed the comparison and are now fixing every page of the REmastered SRD in Markdown format. Plus a new website is under construction and awaiting the updated material. THX!

**Comment by Umbyology** [comment]
Everything updated across the board! Let me know if you spot errors for formatting issues. Reminder, this project is to assist others to publish their own projects and materials. So, things are formatted accordingly. THX!
