### ISSUE TITLE
Create epub with Pandoc

### ISSUE THREAD

**Issue by fedriz** [Umbyology/OGL-SRD5#8]
Hi, I'm wondering if there's a fast way to create an epub for kindle.
Can you help me?

**Comment by raphael-proust** [comment]
`pandoc -f markdown -t epub D\&D\ 5E\ SRD\ v5.1\ Compilation.md -o D\&D\ 5E\ SRD\ v5.1\ Compilation.epub --metadata title='D&D 5E SRD v5.1 Compilation.md'`
Works For ME™

I haven't tried to open the `epub` file that it produces though. Let me know if it works.

**Comment by Umbyology** [comment]
This is a good idea. The above Pandoc process will work if you have Pandoc installed and understand how to use a Terminal, which not everyone does. However, I will make an epub version to download directly from the homepage. Sorry, it took so long for a reply, I was traveling :) ... Stay tuned ... THX!

**Comment by scott-joe** [comment]
I just did the same thing, but for ICML, the Adobe copywriting format so I could take it from Markdown to ICML to InDesign and format it like an antique book. If you'd like, I can write a little script to make it easy for you or anyone else to auto-update these other formats.

Thanks for what you do here!
